evaluate/urls.py
from django.urls import path
from . import views
from .api_views import PersonalEvaluationAPIView
from .api_views import EvlueateAPIView
from .api_views import PostEvaluationAPIView

app_name = 'evaluate'
urlpatterns = [
    path('evaluate_detail/<int:user_id>/<int:pre_user_id>', views.evaluate_detail, name='evaluate_detail'),
    path('evaluate_user/<int:user_id>/', views.evaluate_user, name='evaluate_user'),
    path('evaluate_write/<int:user_id>/<int:target_id>', views.write_review, name='write_review'),
    path('api/personal_evaluation/<int:user_id>', PersonalEvaluationAPIView.as_view(), name='personal-evaluation-api'),
    path('api/evaluate/<int:user_id>', EvlueateAPIView.as_view(), name='evaluate-api'),
    path('api/post/<int:user_id>/<int:target_id>', PostEvaluationAPIView.as_view(), name='post-evaluation-api'),

]

login/urls.py
from django.urls import path
from . import views
from .api_views import LoginAPIView
from .api_views import RegisterAPIView

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('api/login/', LoginAPIView.as_view(), name='login-api'),
    path('api/register/', RegisterAPIView.as_view(), name='register-api'),
]

main_p/urls.py
from django.urls import path
from . import views
from .api_views import MainPAPIView
from .api_views import SearchAPIView
from .api_views import PostAPIView
from .views import new_create_order
from .views import create_sale_order
from .views import create_want_order

app_name = 'main_p'
urlpatterns = [
    path('<int:user_id>', views.index, name='index'),
    path('evaluate_user/<int:user_id>/', views.evaluate_user, name='evaluate_user'),
    path('search/<int:user_id>/', views.search, name='search'),
    path('search_result/<int:user_id>/', views.search_result, name='search_result'),
    path('new_create_order/<int:user_id>/', new_create_order, name='new_create_order'),
    path('create_saleOrder/<int:user_id>/', views.create_sale_order, name='create_saleOrder'),
    path('create_buyOrder/<int:user_id>/', views.create_want_order, name='create_buyOrder'),
    path('index/', views.self_info, name='self_info'),
    path('api/<int:user_id>/', MainPAPIView.as_view(), name='main-p-api'),
    path('api/search/<int:user_id>', SearchAPIView.as_view(), name='search-api'),
    path('api/posts/<int:user_id>/', PostAPIView.as_view(), name='post-api'),
    path('book_detail/<int:user_id>/<str:isbns>/', views.book_detail, name='book_detail'),
]

ntushb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('login.urls')),
    path('main_p/', include('main_p.urls')),
    path('order/', include('order.urls')),
    path('self_info/', include('self_info.urls')),
    path('evaluate/', include('evaluate.urls')),
    path('admin_page/', include('admin_page.urls')),
]

order/urls.py
from django.urls import path
from . import views
from .api_views import SaleOrderAPIView
from .api_views import WantOrderAPIView
from .api_views import SaleOrderDetailAPIView
from .api_views import WantOrderDetailAPIView
from .api_views import ReceiveAPIView

app_name = 'order'
urlpatterns = [
    path('', views.index, name='index'),
    path('want_order/<int:user_id>/', views.want_order, name='want_order'),
    path('sale_order/<int:user_id>/', views.sale_order, name='sale_order'),
    path('want_order/<int:user_id>/detail/<int:order_id>', views.want_order_detail, name='want_order_detail'),
    path('sale_order/<int:user_id>/detail/<int:order_id>', views.sale_order_detail, name='sale_order_detail'),
    path('receive/<int:user_id>/<int:poster_id>/<int:order_id>/<str:type>', views.receive, name='receive'),
    path('api/sale_order/<int:user_id>/<int:page>', SaleOrderAPIView.as_view(), name='sale-order-api'),
    path('api/want_order/<int:user_id>/<int:page>', WantOrderAPIView.as_view(), name='want-order-api'),
    path('api/sale_order_detail/<int:user_id>/<int:order_id>', SaleOrderDetailAPIView.as_view(),
         name='sale-order-detail-api'),
    path('api/want_order_detail/<int:user_id>/<int:order_id>', WantOrderDetailAPIView.as_view(), name='want-order-detail-api'),
    path('api/receive/<int:user_id>/<int:poster_id>/<int:order_id>/<str:type>', ReceiveAPIView.as_view(), name='receive-api'),
]

main_p/forms.py
# forms.py
"""
from django import forms
from django.forms import formset_factory

class SaleOrderForm(forms.Form):
    isbn = forms.CharField(label='ISBN', required=True)
    price = forms.DecimalField(label='Price', required=True)
    description = forms.CharField(label='Description', required=False, widget=forms.Textarea)

SaleOrderFormset = formset_factory(SaleOrderForm, extra=1)
"""
# forms.py
from django import forms

class SaleOrderForm(forms.Form):
    isbn = forms.CharField(label='ISBN', required=True)
    price = forms.DecimalField(label='Price', required=True)
    description = forms.CharField(label='Description', required=False, widget=forms.Textarea)
    
class BuyOrderForm(forms.Form):
    isbn = forms.CharField(label='ISBN', required=True)
    description = forms.CharField(label='Description', required=False, widget=forms.Textarea)

main_p/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
import requests
import json
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from main_p.models import Book
# from .forms import SaleOrderFormset
from .forms import SaleOrderForm
from .forms import BuyOrderForm
from django.forms import formset_factory, BaseFormSet
from django.http import HttpResponseServerError
from django.utils.http import urlencode
from django.db import transaction

app_name = 'main_p'
def index(request, user_id):
    api_url = f'http://localhost:8000/main_p/api/{user_id}'  # Use an f-string to format the URL

    # Making a POST request to the API
    api_response = requests.get(api_url)
    api_response = api_response.json()

    user_info = api_response.get('user')

    #輸入假資訊讓網頁顯示
    if request.method == 'POST':
        #改變html中按鈕的value可以達到按下不同按鈕後，跳轉到不同的頁面
        if request.POST.get('button') == 'self_info':
            return redirect('self_info:index', user_id=user_id)
        elif request.POST.get('button') == 'sale_order':
            return redirect('order:sale_order', user_id=user_id)
        elif request.POST.get('button') == 'want_order':
            return redirect('order:want_order', user_id=user_id)
    return render(request, 'main_p/index.html', {'user_id': user_id, 'user_info': user_info})

def new_create_order(request, user_id):
    return render(request, 'main_p/new_create_order.html', {'user_id': user_id})

def create_sale_order(request, user_id):
    if request.method == 'POST':
        isbn_input = request.POST.get('ISBN')
        isbns = isbn_input.split('、') if isbn_input else []
        price_input = request.POST.get('Price')
        prices = price_input.split('、') if price_input else []
        description_input = request.POST.get('Description')
        descriptions = description_input.split('、') if description_input else []

        detail_require = 0
        detail_isbn = []
        for isbn in isbns:
        # Check if the ISBN already exists in the database
            book_exists = Book.objects.filter(isbn=isbn).exists()
            if not book_exists:
                detail_require += 1
                detail_isbn.append(isbn)
        query_params = urlencode({
            'all_isbns': "、".join(isbns),
            'prices': "、".join(prices),
            'descriptions': "、".join(descriptions),
            'type': 'sell',
        })

        if len(detail_isbn) == 0:
            # Handle the case where there are no ISBNs, you can redirect to a different URL or handle it as needed
            redirect_url = f'/main_p/book_detail/{user_id}/no_isbn/?{query_params}'
            # If only one ISBN, use it directly in the path instead of joining a list
        elif len(detail_isbn) == 1:
            redirect_url = f'/main_p/book_detail/{user_id}/{detail_isbn[0]}/?{query_params}'
        else:
            redirect_url = f'/main_p/book_detail/{user_id}/{"、".join(detail_isbn)}/?{query_params}'

        # Redirect to the constructed URL
        return redirect(redirect_url)
    return render(request, 'main_p/create_saleOrder.html', {'user_id': user_id})


def create_want_order(request, user_id):
    if request.method == 'POST':
        isbn_input = request.POST.get('ISBN')
        isbns = isbn_input.split('、') if isbn_input else []
        description_input = request.POST.get('Description')
        descriptions = description_input.split('、') if description_input else []

        detail_require = 0
        detail_isbn = []
        for isbn in isbns:
            # Check if the ISBN already exists in the database
            book_exists = Book.objects.filter(isbn=isbn).exists()
            if not book_exists:
                detail_require += 1
                detail_isbn.append(isbn)
        query_params = urlencode({
            'all_isbns': "、".join(isbns),
            'descriptions': "、".join(descriptions),
            'type': 'want',
        })

        if len(detail_isbn) == 0:
            # Handle the case where there are no ISBNs, you can redirect to a different URL or handle it as needed
            redirect_url = f'/main_p/book_detail/{user_id}/no_isbn/?{query_params}'
            # If only one ISBN, use it directly in the path instead of joining a list
        elif len(detail_isbn) == 1:
            redirect_url = f'/main_p/book_detail/{user_id}/{detail_isbn[0]}/?{query_params}'
        else:
            redirect_url = f'/main_p/book_detail/{user_id}/{"、".join(detail_isbn)}/?{query_params}'

        # Redirect to the constructed URL
        return redirect(redirect_url)
    return render(request, 'main_p/create_buyOrder.html', {'user_id': user_id})

def book_detail(request, user_id, isbns):
    with transaction.atomic():
        api_url = f'http://localhost:8000/main_p/api/posts/{user_id}/'
        isbns_list = isbns.split('、') if isbns else []
        all_isbns = request.GET.get('all_isbns').split('、') if request.GET.get('all_isbns') else []
        print('cicndicninwdn', all_isbns)
        prices = request.GET.get('prices').split('、') if request.GET.get('prices') else []
        descriptions = request.GET.get('descriptions').split('、') if request.GET.get('descriptions') else []
        type = request.GET.get('type')
        data = {
            'all_isbns': all_isbns,
            'prices': prices,
            'descriptions': descriptions,
            'order_type': type
        }

        if isbns_list[0] == 'no_isbn':
            response = requests.get(api_url, json=data)
            api_response = response.json()
            order_id = api_response.get('order_id')
            if type == 'sell':
                return redirect('self_info:posting_sell_detail', user_id=user_id, order_id=order_id)
            else:
                return redirect('self_info:posting_want_detail', user_id=user_id, order_id=order_id)
        else:
            if request.method == 'POST':
                isbns = request.POST.getlist('ISBN')
                book_titles = request.POST.getlist('bookTitle')
                authors = request.POST.getlist('author')
                categories = request.POST.getlist('category')
                course_ids = request.POST.getlist('courseID')
                academic_years = request.POST.getlist('academic_year')
                course_names = request.POST.getlist('course_name')
                instructor_names = request.POST.getlist('instructor_name')
                # Zip the lists together to iterate over corresponding elements
                for isbn, title, author, category, course_id, academic_year, course_name, instructor_name in zip(
                        isbns, book_titles, authors, categories, course_ids, academic_years, course_names, instructor_names
                ):
                    form_data = {
                        'ISBN': isbn,
                        'bookTitle': title,
                        'author': author,
                        'category': category,
                        'courseID': course_id,
                        'academic_year': academic_year,
                        'course_name': course_name,
                        'instructor_name': instructor_name,
                    }
                    response = requests.post(api_url, json=form_data)
                    api_response = response.json()
                response = requests.get(api_url, json=data)
                api_response = response.json()
                order_id = api_response.get('order_id')
                if type == 'sell':
                    return redirect('self_info:posting_sell_detail', user_id=user_id, order_id=order_id)
                else:
                    return redirect('self_info:posting_want_detail', user_id=user_id, order_id=order_id)
    return render(request, 'main_p/book_detail.html', {'user_id': user_id, 'isbns': isbns_list})


def search(request, user_id):
    if request.method == 'POST':
        api_url = f'http://localhost:8000/main_p/api/search/{user_id}'
        order_type = request.POST.get('order_type')
        category = request.POST.get('category')
        keyword = request.POST.get('keyword')

        form_data = {"order_type": order_type,
                     "category": category,
                     "keyword": keyword
                    }

        api_response = requests.post(api_url, json=form_data)
        api_response = api_response.json()
        orders = api_response.get('orders')
        # Process form data and save to the database
        return render(request, 'main_p/search_result.html', {'orders': orders, 'user_id': user_id})
    return render(request, 'main_p/search.html', {'user_id': user_id})
        
def search_result(request, user_id):
    if request.method == 'POST':
        # Process form data and save to the database
        return render(request, 'main_p/search_result.html', {'user_id': user_id})
    else:
        return render(request, 'main_p/search_result.html', {'user_id': user_id})
    
def evaluate_user(request, user_id):
    if request.method == 'POST':
        # Process form data and save to the database
        return render(request, 'evaluate/evaluate_user.html', {'user_id': user_id})
    else:
        return render(request, 'evaluate/evaluate_user.html', {'user_id': user_id})
        
def self_info(request, user_id):
    api_url = f'http://localhost:8000/main_p/api/{user_id}'  # Use an f-string to format the URL

    if request.method == 'POST':
        # Process form data and save to the database
        # If you need to make a POST request, use requests.post()
        api_response = requests.post(api_url, data=request.POST)
    else:
        # Making a GET request to the API
        api_response = requests.get(api_url)

    api_data = api_response.json()
    user_info = api_data.get('user')

    return render(request, 'self_info/index.html', {'user_id': user_id, 'user_info': user_info})

main_p/templates/main_p/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>書籍詳細資訊</title>
    <style>

        form {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            grid-gap: 10px;
            max-width: 400px;
            width: 100%;
        }

        label {
            grid-column: span 2;
        }

        button {
            width=70px;
        }
    </style>
</head>
<body>

<h2>填寫書籍詳細資訊</h2>
{% for isbn in isbns %}
	<form method="post">
		{% csrf_token %}
		
		<input type="hidden" name="ISBN" value="{{ isbn }}">
		
		<label for="ISBN">ISBN：{{ isbn }}</label>
		<label for="bookTitle">書名</label>
		<input type="text" id="bookTitle" name="bookTitle" required><br>

		<label for="author">作者</label>
		<input type="text" id="author" name="author" required><br>

		<label for="category">類別</label>
		<select id="category" name="category" required>
			<option value="1">1</option>
			<option value="2">2</option>
			<option value="3">3</option>
			<option value="4">4</option>
			<option value="5">5</option>
			<option value="6">6</option>
			<option value="7">7</option>
		</select><br>

		<label for="courseID">台大課程識別碼</label>
		<input type="text" id="courseID" name="courseID" required><br>

		<label for="academicYear">開課學年度</label>
		<input type="text" id="academicYear" name="academic_year" required><br>

		<label for="courseName">課程名稱</label>
		<input type="text" id="courseName" name="course_name" required><br>

		<label for="instructorName">教師名稱</label>
		<input type="text" id="instructorName" name="instructor_name" required><br>
		
		<label for="line">======================</label>
        {% if forloop.last %}
            <!-- Submit button inside the last form -->
            <button type="submit">提交</button>
        {% endif %}
	</form>
{% endfor %}
</body>
</html>

main_p/templates/main_p/create_buyOrder.html
<!-- create_buyOrder.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Buy Order</title>
</head>
<style>
    label {
        display: inline-block;
        width: 100px; /* Adjust the width as needed */
        margin-bottom: 5px; /* Add margin to create space below each label */
    }

    textarea {
        vertical-align: top;
        margin-bottom: 10px; /* Add margin to create space below each textarea */
    }

    button {
        margin-top: 10px; /* Add margin to create space above the button */
    }
</style>

<body>

    <h2>新增徵求訂單</h2>
	<h3>若要新增多本書籍，ISBN 和 Description 請用全形頓號(、)隔開</h3>
	<form action="{% url 'main_p:create_saleOrder' user_id=user_id %}" method="post">
	 {% csrf_token %}
	<div>
		<label for="ISBN">ISBN</label>
        <textarea name="ISBN" id="ISBN" rows="1"></textarea>
	</div>
	<div>	
		<label for="Description">Description</label>
        <textarea name="Description" id="Description" rows="4"></textarea>
	</div>
	<div>	
		<button type="submit">提交</button>
    </div>
	</form>

</body>
</html>

main_p/templates/main_p/create_saleOrder.html
<!-- create_saleOrder.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Sale Order</title>
</head>
<style>
    label {
        display: inline-block;
        width: 100px; /* Adjust the width as needed */
        margin-bottom: 5px; /* Add margin to create space below each label */
    }

    textarea {
        vertical-align: top;
        margin-bottom: 10px; /* Add margin to create space below each textarea */
    }

    button {
        margin-top: 10px; /* Add margin to create space above the button */
    }
</style>

<body>

    <h2>新增販賣訂單</h2>
	<h3>若要新增多本書籍，ISBN 和 Price 和 Description 請用全形頓號(、)隔開</h3>
	<form action="{% url 'main_p:create_saleOrder' user_id=user_id %}" method="post">
	 {% csrf_token %}
	<div>
		<label for="ISBN">ISBN</label>
        <textarea name="ISBN" id="ISBN" rows="1"></textarea>
	</div>
	<div>
		<label for="Price">Price</label>
        <textarea name="Price" id="Price" rows="1"></textarea>
	</div>
	<div>	
		<label for="Description">Description</label>
        <textarea name="Description" id="Description" rows="4"></textarea>
	</div>
	<div>	
		<button type="submit">提交</button>
    </div>
	</form>

</body>
</html>

main_p/templates/main_p/index.html
<!DOCTYPE html>
<html>
<head>
    <title>NTUSHB</title>
    <style>
        body {
            text-align: center;
        }
        #login-form {
            margin: 50px auto;
            width: 30%;
            padding: 20px;
            border: 1px solid #ccc;
            box-shadow: 2px 2px 10px #ccc;
        }
        #title {
            background-color: #f8f8f8;
            color: #333;
            padding: 10px 20px;
            text-align: center;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

		.custom-button {
        background-color:#E0E0E0;
        color: black;
        padding: 10px 15px;
        border: None;
        border-radius: 4px;
        cursor: pointer;
		width: 150px;
		margin-bottom: 10px;
		}

		.custom-button:hover {
			background-color:#66B3FF;
    </style>
</head>
<body>
    <div id="title">
        <!-- 像這樣可以顯示輸入的user的資訊 -->
        <h1>NTUSHB - 您好！{{ user_info.username }}</h1>
    </div>
    <div id="login-form">
        <form method="post">
            {% csrf_token %}
			<div>
				<button type="submit" name="button" value="self_info" class="custom-button">個人資訊</button>

				<input type="button" value="新增" class="custom-button" onclick="location.href='{% url 'main_p:new_create_order' user_id=user_id%}'">
			</div>

			<div>
				<button type="submit" name="button" value="sale_order" class="custom-button">查看所有販賣訂單</button>
				<button type="submit" name="button" value="want_order" class="custom-button">查看所有徵求訂單</button>
			</div>
			<div>
				<input type="button" value="查詢" class="custom-button" onclick="location.href='{% url 'main_p:search' user_id=user_id%}'">
				<input type="button" value="評價" class="custom-button" onclick="location.href='{% url 'evaluate:evaluate_user' user_id=user_id %}'">
			</div>
        </form>
</body>

main_p/templates/main_p/new_create_order.html
<!-- create_order.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Order</title>
    <style>
         body {
            font-family: Arial, sans-serif;
        }

        h1 {
            text-align: center;
        }

        form {
            max-width: 600px;
            margin: 0 auto;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input,
        select,
        textarea {
            width: 100%;
            padding: 8px;
            margin-bottom: 15px;
            box-sizing: border-box;
        }

        button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }
		
		.custom-button {
        background-color: #4CAF50;
        color: white;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
		width: 70px;
		}

		.custom-button:hover {
			background-color: #45a049;

    </style>
</head>

<body>

    <h2>新增訂單</h2>

    <form method="post" action="{% url 'main_p:new_create_order' user_id=user_id%}" id="orderForm">
	
	<input type="button" value="販賣" class="custom-button" onclick="location.href='{% url 'main_p:create_saleOrder' user_id=user_id%}'">
	
	<input type="button" value="徵求" class="custom-button" onclick="location.href='{% url 'main_p:create_buyOrder' user_id=user_id%}'">
	
</body>
</html>

main_p/templates/main_p/search.html
<!-- search_orders.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Orders</title>
	<style>
        body {
            font-family: Arial, sans-serif;
        }

        h1 {
            text-align: center;
        }
        p {
            text-align: center;
        }
        form {
            max-width: 600px;
            margin: 0 auto;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input,
        select,
        textarea {
            width: 100%;
            padding: 8px;
            margin-bottom: 15px;
            box-sizing: border-box;
        }
		.custom-button {
        background-color: #4CAF50;
        color: white;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
		width: 70px;
		}

		.custom-button:hover {
			background-color: #45a049;
	}
    </style>
</head>
<body>

<h1>查詢訂單</h1>
<p><a href="/main_p/{{user_id}}">回主頁</a></p>
<form method="post" action="{% url 'main_p:search' user_id=user_id %}">
    {% csrf_token %}

    <label for="order_type">訂單種類</label>
    <select id="order_type" name="order_type">
        <option value="sell">販賣</option>
        <option value="buy">徵求</option>
    </select>

    <label for="category">類別</label>
    <select id="category" name="category">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
    </select>

    <label for="keyword">關鍵字(非必填項目)</label>
    <input type="text" id="keyword" name="keyword">

    <form method="post" action="{% url 'main_p:search_result' user_id=user_id%}">
    {% csrf_token %}
    <!-- Form fields -->

<button type="submit">Submit</button>

</form>
<P>類別說明：<P>
	<li>
	1：理、工、電資學院
	</li>
	<li>
	2：文、法、社科學院
	</li>
	<li>
	3：生科、生農學院
	</li>
	<li>
	4：醫、工衛學院
	</li>
	<li>
	5：管理、創新設計學院
	</li>
	<li>
	6：國際學院、重點科技研究學院、共同教育中心、進修
	推廣學院
	</li>
	<li>
	7：通識、共同必修、非課程用書
	</li>



</body>
</html>

main_p/templates/main_p/search_result.html
<!-- search_results.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Results</title>
	    <style>
        body {
            text-align: center;
        }
        #login-form {
            margin: 50px auto;
            width: 30%;
            padding: 20px;
            border: 1px solid #ccc;
            box-shadow: 2px 2px 10px #ccc;
        }
        #title {
            background-color: #f8f8f8;
            color: #333;
            padding: 10px 20px;
            text-align: left;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
		button {
            background-color: #DDDDDD;
            color: black;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #DDDDDD;
        }
    </style>
</head>
<body>

<h1>查詢結果</h1>
<!-- 加分頁 -->
{% for page in orders.paginator.page_range %}
    a href="?page={{ page }}">{{ page }}</a>
{% endfor %}

{% if orders %}
    <ul>
        {% for order in orders %}
		<h2><a href="{% url 'order:sale_order_detail' user_id=user_id order_id=order.order_id  %}">訂單編號: {{ order.order_id }}</a></h2>
    <ul>
        {% for book in order.books %}
            <li>
                書籍資訊：
                ISBN: {{ book.isbn }}, 
                價格: {{ book.price }},
                書名: {{ book.title }}
            </li>
        {% endfor %}
        <li>
            ---------------------------------------------------------------------------------------
        </li>
    </ul>
    {% endfor %}
    </ul>
{% else %}
    <p>No orders found.</p>
{% endif %}

<button onclick="location.href='{% url 'main_p:search' user_id=user_id%}'">返回</button>
</body>
</html>