evaluate/urls.py
from django.urls import path
from . import views
from .api_views import PersonalEvaluationAPIView
from .api_views import EvlueateAPIView
from .api_views import PostEvaluationAPIView

app_name = 'evaluate'
urlpatterns = [
    path('evaluate_detail/<int:user_id>/<int:pre_user_id>', views.evaluate_detail, name='evaluate_detail'),
    path('evaluate_user/<int:user_id>/', views.evaluate_user, name='evaluate_user'),
    path('evaluate_write/<int:user_id>/<int:target_id>', views.write_review, name='write_review'),
    path('api/personal_evaluation/<int:user_id>', PersonalEvaluationAPIView.as_view(), name='personal-evaluation-api'),
    path('api/evaluate/<int:user_id>', EvlueateAPIView.as_view(), name='evaluate-api'),
    path('api/post/<int:user_id>/<int:target_id>', PostEvaluationAPIView.as_view(), name='post-evaluation-api'),

]

login/urls.py
from django.urls import path
from . import views
from .api_views import LoginAPIView
from .api_views import RegisterAPIView

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('api/login/', LoginAPIView.as_view(), name='login-api'),
    path('api/register/', RegisterAPIView.as_view(), name='register-api'),
]

ntushb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('login.urls')),
    path('main_p/', include('main_p.urls')),
    path('order/', include('order.urls')),
    path('self_info/', include('self_info.urls')),
    path('evaluate/', include('evaluate.urls')),
    path('admin_page/', include('admin_page.urls')),
]

self_info/urls.py
from django.urls import path
from . import views
from .api_views import FinishAPIView
from .api_views import FinishSellAPIView
from .api_views import FinishWantAPIView
from .api_views import PostingSellAPIView
from .api_views import PostingWantAPIView
from .api_views import PostingAPIView
from .api_views import ReceiveAPIView
from .api_views import ReceiveSellAPIView
from .api_views import ReceiveWantAPIView
from .api_views import RenewStatusAPIView

app_name = 'self_info'
urlpatterns = [
    path('<int:user_id>/', views.index, name='index'),
    path('personal_order/<int:user_id>', views.personal_order, name='personal_order'),
    path('personal_order/finish/<int:user_id>', views.finish, name='finish'),
    path('personal_order/posting/<int:user_id>/', views.posting, name='posting'),
    path('personal_order/received/<int:user_id>', views.received, name='received'),
    path('personal_order/finish/<int:user_id>/finish_sell_detail/<int:order_id>', views.finish_sell_detail, name='finish_sell_detail'),
    path('personal_order/finish/<int:user_id>/posting_sell_detail/<int:order_id>', views.posting_sell_detail, name='posting_sell_detail'),
    path('personal_order/finish/<int:user_id>/received_sell_detail/<int:order_id>', views.received_sell_detail, name='received_sell_detail'),
    path('personal_order/finish/<int:user_id>/finish_want_detail/<int:order_id>', views.finish_want_detail, name='finish_want_detail'),
    path('personal_order/finish/<int:user_id>/posting_want_detail/<int:order_id>', views.posting_want_detail, name='posting_want_detail'),
    path('personal_order/finish/<int:user_id>/received_want_detail/<int:order_id>', views.received_want_detail, name='received_want_detail'),
    path('DBMS_final/evaluate/templates/evaluate/evaluate_detail/<int:order_id>', views.evaluate_detail, name='evaluate_detail'),
    path('api/finish/<int:user_id>/', FinishAPIView.as_view(), name='finish-api'),
    path('api/finish_sell_detail/<int:user_id>/<int:order_id>', FinishSellAPIView.as_view(), name='finish-sell-api'),
    path('api/finish_want_detail/<int:user_id>/<int:order_id>', FinishWantAPIView.as_view(), name='finish-want-api'),
    path('api/posting_sell_detail/<int:user_id>/<int:order_id>', PostingSellAPIView.as_view(), name='posting-sell-api'),
    path('api/posting_want_detail/<int:user_id>/<int:order_id>', PostingWantAPIView.as_view(), name='posting-want-api'),
    path('api/posting/<int:user_id>/', PostingAPIView.as_view(), name='posting-api'),
    path('api/receive/<int:user_id>/', ReceiveAPIView.as_view(), name='receive-api'),
    path('api/receive_sell_detail/<int:user_id>/<int:order_id>', ReceiveSellAPIView.as_view(), name='receive-sell-api'),
    path('api/receive_want_detail/<int:user_id>/<int:order_id>', ReceiveWantAPIView.as_view(), name='receive-want-api'),
    path('api/renew', RenewStatusAPIView.as_view(), name='renew-status-api'),

]

self_info/models.py
from django.db import models

# Create your models here.
class User:
    def __init__(self, user_id, user_name, role='user'):
        self.user_id = user_id
        self.user_name = user_name
        self.role = role


class Book_object:
    def __init__(self, isbn, price, description, receiver, status, title, author):
        self.isbn = isbn
        self.price = price
        self.description = description
        self.status = status
        self.receiver = receiver
        self.title = title
        self.author = author


class Order:
    def __init__(self, order_id, user_id, books):
        self.order_id = order_id
        self.user_id = user_id
        self.books = books

    class Meta:
        managed = True


class Book_detail:
    def __init__(self, isbn, price, description, receiver, status,
                 title, author, category, courseID, academic_year, course_name, teacher_name):
        self.isbn = isbn
        self.price = price
        self.description = description
        self.status = status
        self.receiver = receiver
        self.title = title
        self.author = author
        self.category = category
        self.courseID = courseID
        self.academic_year = academic_year
        self.courseName = course_name
        self.teacherName = teacher_name

self_info/views.py
from django.shortcuts import render,redirect
import requests
import json
from django.urls import reverse
from django.utils.http import urlencode


app_name = 'self_info'
def index(request, user_id):
    api_url = f'http://localhost:8000/main_p/api/{user_id}'
    if request.method == 'POST':
        api_response = requests.post(api_url, data=request.POST)
        #改變html中按鈕的value可以達到按下不同按鈕後，跳轉到不同的頁面
        if request.POST.get('button') == 'personal_order':
            return redirect('self_info:personal_order', user_id=user_id)
    else:
        # Making a GET request to the API
        api_response = requests.get(api_url)

    api_data = api_response.json()
    user_info = api_data.get('user')
    return render(request, 'self_info/index.html', {'user_id': user_id, 'user_info': user_info})

def personal_order(request, user_id):
    if request.method == 'POST':
        #改變html中按鈕的value可以達到按下不同按鈕後，跳轉到不同的頁面
        if request.POST.get('button') == 'finished_order':
            return redirect('self_info:finish', user_id=user_id)
        if request.POST.get('button') == 'posting_order':
            return redirect('self_info:posting', user_id=user_id)
        if request.POST.get('button') == 'received_order':
            return redirect('self_info:received', user_id=user_id)
    return render(request, 'self_info/personal_order.html', {'user_id': user_id})

def finish(request, user_id):
    api_url = f'http://localhost:8000/self_info/api/finish/{user_id}'
    api_response = requests.get(api_url)
    api_response = api_response.json()
    orders = api_response.get('orders')
    want_orders = api_response.get('want_orders')
    return render(request, 'self_info/finish.html',  {'orders': orders,'user_id': user_id, 'want_orders': want_orders})

def posting(request, user_id):
    api_url = f'http://localhost:8000/self_info/api/posting/{user_id}'
    api_response = requests.get(api_url)
    api_response = api_response.json()
    orders = api_response.get('orders')
    want_orders = api_response.get('want_orders')
    return render(request, 'self_info/posting.html', {'orders': orders,'user_id': user_id, 'want_orders': want_orders})
def received(request, user_id):
    # 創建假用戶數據
    api_url = f'http://localhost:8000/self_info/api/receive/{user_id}'
    api_response = requests.get(api_url)
    api_response = api_response.json()
    orders = api_response.get('orders')
    want_orders = api_response.get('want_orders')
    return render(request, 'self_info/received.html', {'orders': orders,'user_id': user_id, 'want_orders': want_orders})

def finish_sell_detail(request, order_id, user_id):
    api_url = f'http://localhost:8000/self_info/api/finish_sell_detail/{user_id}/{order_id}'
    api_response = requests.get(api_url)
    api_response = api_response.json()
    books = api_response.get('books')
    receivers = api_response.get('receivers')
    
    if request.method == 'POST':
        for key, value in request.POST.items():
                if value == 'evaluate':
                    evaluated_user_id = int(key.split('_')[1])
                    return redirect('evaluate:evaluate_detail', user_id=evaluated_user_id, pre_user_id=user_id)
    return render(request, 'self_info/detail/finish_sell_detail.html', {'books': books,'user_id': user_id,
                                                                        'order_id': order_id, 'receivers': receivers})

def posting_sell_detail(request, order_id, user_id):
    api_url = f'http://localhost:8000/self_info/api/posting_sell_detail/{user_id}/{order_id}'
    api_response = requests.get(api_url)
    api_response = api_response.json()
    books = api_response.get('books')
    receivers = api_response.get('receivers')

    if request.method == 'POST':
        # 檢查每個按鈕
        for key, value in request.POST.items():
                if value == 'evaluate':
                    evaluated_user_id = int(key.split('_')[1])
                    return redirect('evaluate:evaluate_detail', user_id=evaluated_user_id, pre_user_id=user_id)
                elif value == 'renew':
                    # 處理更新狀態的按鈕
                    # 從按鈕名稱中提取書籍的 isbn 和訂單 ID
                    parts = key.split('_')
                    renew_isbn = parts[1]
                    renew_order_id = int(parts[2])
                    renew_status = request.POST.get(f'status_{renew_isbn}')
                    data = {
                        'order_id': renew_order_id,
                        'isbn': renew_isbn,
                        'status': renew_status,
                        'type': 'sell',
                    }
                    url = f'http://localhost:8000/self_info/api/renew'
                    response = requests.post(url, json=data)
                    return redirect(request.path)

    return render(request, 'self_info/detail/posting_sell_detail.html', {'books': books,'user_id': user_id, 'order_id': order_id, 'receivers': receivers})

def received_sell_detail(request, order_id, user_id):
    api_url = f'http://localhost:8000/self_info/api/receive_sell_detail/{user_id}/{order_id}'
    api_response = requests.get(api_url)
    api_response = api_response.json()
    books = api_response.get('books')

    if request.method == 'POST':
        for key, value in request.POST.items():
                if value == 'evaluate':
                    evaluated_user_id = int(key.split('_')[1])
                    return redirect('evaluate:evaluate_detail', user_id=evaluated_user_id, pre_user_id=user_id)
    return render(request, 'self_info/detail/received_sell_detail.html', {'books': books,'user_id': user_id, 'order_id': order_id})

def finish_want_detail(request, order_id, user_id):
    api_url = f'http://localhost:8000/self_info/api/finish_want_detail/{user_id}/{order_id}'
    api_response = requests.get(api_url)
    api_response = api_response.json()
    books = api_response.get('books')
    receivers = api_response.get('receivers')


    if request.method == 'POST':
        for key, value in request.POST.items():
                if value == 'evaluate':
                    evaluated_user_id = int(key.split('_')[1])
                    return redirect('evaluate:evaluate_detail', user_id=evaluated_user_id, pre_user_id=user_id)
    return render(request, 'self_info/detail/finish_want_detail.html', {'books': books,'user_id': user_id, 'order_id': order_id, 'receivers': receivers})

def posting_want_detail(request, order_id, user_id):
    api_url = f'http://localhost:8000/self_info/api/posting_want_detail/{user_id}/{order_id}'
    api_response = requests.get(api_url)
    api_response = api_response.json()
    books = api_response.get('books')
    receivers = api_response.get('receivers')
    if request.method == 'POST':
        # 檢查每個按鈕
        for key, value in request.POST.items():
                if value == 'evaluate':
                    evaluated_user_id = int(key.split('_')[1])
                    return redirect('evaluate:evaluate_detail', user_id=evaluated_user_id, pre_user_id=user_id)
                elif value == 'renew':
                    # 處理更新狀態的按鈕
                    # 從按鈕名稱中提取書籍的 isbn 和訂單 ID
                    parts = key.split('_')
                    renew_isbn = parts[1]
                    renew_order_id = int(parts[2])
                    renew_status = request.POST.get(f'status_{renew_isbn}')
                    data = {
                        'order_id': renew_order_id,
                        'isbn': renew_isbn,
                        'status': renew_status,
                        'type': 'want',
                    }
                    url = f'http://localhost:8000/self_info/api/renew'
                    response = requests.post(url, json=data)
                    url = reverse('self_info:posting_want_detail', kwargs={'user_id': user_id, 'order_id': order_id})

                    return redirect(url)

    return render(request, 'self_info/detail/posting_want_detail.html', {'books': books,'user_id': user_id, 'order_id': order_id, 'receivers': receivers})

def received_want_detail(request, order_id, user_id):
    api_url = f'http://localhost:8000/self_info/api/receive_want_detail/{user_id}/{order_id}'
    api_response = requests.get(api_url)
    api_response = api_response.json()
    books = api_response.get('books')
    if request.method == 'POST':
        for key, value in request.POST.items():
                if value == 'evaluate':
                    print(key)
                    evaluated_user_id = int(key.split('_')[1])
                    return redirect('evaluate:evaluate_detail', user_id=evaluated_user_id, pre_user_id=user_id)
    return render(request, 'self_info/detail/received_want_detail.html', {'books': books,'user_id': user_id, 'order_id': order_id})
    
def evaluate_detail(request, user_id):
    # Your view logic here
    if request.method == 'POST':
        # Process form data and save to the database
        return render(request, 'evaluate/evaluate_detail.html', {'user_id': user_id})
    else:
        return render(request, 'evaluate/evaluate_detail.html', {'user_id': user_id})

self_info/templates/self_info/finish.html
<!DOCTYPE html>
<html>
<head>
    <title>NTUSHB</title>
    <style>
        body {
            text-align: center;
        }
        #login-form {
            margin: 50px auto;
            width: 30%;
            padding: 20px;
            border: 1px solid #ccc;
            box-shadow: 2px 2px 10px #ccc;
        }
        #title {
            background-color: #f8f8f8;
            color: #333;
            padding: 10px 20px;
            text-align: left;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div id="title">
        <!-- 像這樣可以顯示輸入的user的資訊 -->
        <h1>NTUSHB - 已完成訂單</h1> 
        <p><a href="/main_p/{{user_id}}">回主頁</a></p>
    </div>
    <h1>販賣訂單</h1> 
    {% for order in orders %}
    <h2><a href="{% url 'self_info:finish_sell_detail' user_id=user_id order_id=order.order_id  %}">訂單編號: {{ order.order_id }}</a></h2>
    <ul>
        {% for book in order.books %}
            <li>
                書籍資訊：
                ISBN: {{ book.isbn }}, 
                價格: {{ book.price }},
                書名: {{ book.title }}
            </li>
        {% endfor %}
        <li>
            ---------------------------------------------------------------------------------------
        </li>
    </ul>
    {% endfor %}
    <h1>徵求訂單</h1> 
    {% for order in want_orders %}
    <h2><a href="{% url 'self_info:finish_want_detail' user_id=user_id order_id=order.order_id  %}">訂單編號: {{ order.order_id }}</a></h2>
    <ul>
        {% for book in order.books %}
            <li>
                書籍資訊：
                ISBN: {{ book.isbn }}, 
                書名: {{ book.title }}
            </li>
        {% endfor %}
        <li>
            ---------------------------------------------------------------------------------------
        </li>
    </ul>
    {% endfor %}
</body>

self_info/templates/self_info/index.html
<!DOCTYPE html>
<html>
<head>
    <title>NTUSHB</title>
    <style>
        body {
            text-align: center;
        }
        #login-form {
            margin: 50px auto;
            width: 30%;
            padding: 20px;
            border: 1px solid #ccc;
            box-shadow: 2px 2px 10px #ccc;
        }
        #title {
            background-color: #f8f8f8;
            color: #333;
            padding: 10px 20px;
            text-align: center;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div id="title">
        <!-- 像這樣可以顯示輸入的user的資訊 -->
        <h1>NTUSHB - 個人資訊頁</h1> 
        <p><a href="/main_p/{{user_id}}">回主頁</a></p>
    </div>
    <div id="login-form">
		<p>姓名：{{user_info.username}}</p>
		<p>信箱：{{user_info.email}}</p>
		
		<button onclick="location.href='{% url 'evaluate:evaluate_detail' user_id=user_id pre_user_id=user_id %}'">瀏覽所有評價</button>
        <form method="post">
            {% csrf_token %}
            <button type="submit" name="button" value="personal_order">瀏覽訂單紀錄</button>
        </form>
		
    </div>
</body>

self_info/templates/self_info/personal_order.html
<!DOCTYPE html>
<html>
<head>
    <title>NTUSHB</title>
    <style>
        body {
            text-align: center;
        }
        #login-form {
            margin: 50px auto;
            width: 30%;
            padding: 20px;
            border: 1px solid #ccc;
            box-shadow: 2px 2px 10px #ccc;
        }
        #title {
            background-color: #f8f8f8;
            color: #333;
            padding: 10px 20px;
            text-align: left;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div id="title">
        <!-- 像這樣可以顯示輸入的user的資訊 -->
        <h1>NTUSHB - 個人訂單頁</h1> 
        <p><a href="/main_p/{{user_id}}">回主頁</a></p>
    </div>
    <div id="login-form">
        <form method="post">
            {% csrf_token %}
            <button type="submit" name="button" value="finished_order">已完成訂單</button>
            <button type="submit" name="button" value="posting_order">張貼中訂單</button>
            <button type="submit" name="button" value="received_order">已接受訂單</button>
        </form>
    </div>
</body>

self_info/templates/self_info/posting.html
<!DOCTYPE html>
<html>
<head>
    <title>NTUSHB</title>
    <style>
        body {
            text-align: center;
        }
        #login-form {
            margin: 50px auto;
            width: 30%;
            padding: 20px;
            border: 1px solid #ccc;
            box-shadow: 2px 2px 10px #ccc;
        }
        #title {
            background-color: #f8f8f8;
            color: #333;
            padding: 10px 20px;
            text-align: left;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div id="title">
        <!-- 像這樣可以顯示輸入的user的資訊 -->
        <h1>NTUSHB 張貼中訂單</h1> 
        <p><a href="/main_p/{{user_id}}">回主頁</a></p>
    </div>
    <h1>販賣訂單</h1> 
    {% for order in orders %}
    <h2><a href="{% url 'self_info:posting_sell_detail' user_id=user_id order_id=order.order_id  %}">訂單編號: {{ order.order_id }}</a></h2>
    <ul>
        {% for book in order.books %}
            <li>
                書籍資訊：
                ISBN: {{ book.isbn }}, 
                價格: {{ book.price }},
                書名: {{ book.title }}
            </li>
        {% endfor %}
        <li>
            ---------------------------------------------------------------------------------------
        </li>
    </ul>
    {% endfor %}
    <h1>徵求訂單</h1> 
    {% for order in want_orders %}
    <h2><a href="{% url 'self_info:posting_want_detail' user_id=user_id order_id=order.order_id  %}">訂單編號: {{ order.order_id }}</a></h2>
    <ul>
        {% for book in order.books %}
            <li>
                書籍資訊：
                ISBN: {{ book.isbn }}, 
                書名: {{ book.title }}
            </li>
        {% endfor %}
        <li>
            ---------------------------------------------------------------------------------------
        </li>
    </ul>
    {% endfor %}
</body>

self_info/templates/self_info/received.html
<!DOCTYPE html>
<html>
<head>
    <title>NTUSHB</title>
    <style>
        body {
            text-align: center;
        }
        #login-form {
            margin: 50px auto;
            width: 30%;
            padding: 20px;
            border: 1px solid #ccc;
            box-shadow: 2px 2px 10px #ccc;
        }
        #title {
            background-color: #f8f8f8;
            color: #333;
            padding: 10px 20px;
            text-align: left;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div id="title">
        <!-- 像這樣可以顯示輸入的user的資訊 -->
        <h1>NTUSHB 已接受訂單</h1> 
        <p><a href="/main_p/{{user_id}}">回主頁</a></p>
    </div>
    <h1>販賣訂單</h1>
    {% for order in orders %}
    <h2><a href="{% url 'self_info:received_sell_detail' user_id=user_id order_id=order.order_id  %}">訂單編號: {{ order.order_id }}</a></h2>
    <ul>
        {% for book in order.books %}
            <li>
                書籍資訊：
                ISBN: {{ book.isbn }}, 
                價格: {{ book.price }},
                書名: {{ book.title }}
            </li>
        {% endfor %}
        <li>
            ---------------------------------------------------------------------------------------
        </li>
    </ul>
    {% endfor %}
    <h1>徵求訂單</h1> 
    {% for order in want_orders %}
    <h2><a href="{% url 'self_info:received_want_detail' user_id=user_id order_id=order.order_id  %}">訂單編號: {{ order.order_id }}</a></h2>
    <ul>
        {% for book in order.books %}
            <li>
                書籍資訊：
                ISBN: {{ book.isbn }}, 
                書名: {{ book.title }}
            </li>
        {% endfor %}
        <li>
            ---------------------------------------------------------------------------------------
        </li>
    </ul>
    {% endfor %}
</body>