login/urls.py
from django.urls import path
from . import views
from .api_views import LoginAPIView
from .api_views import RegisterAPIView

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('api/login/', LoginAPIView.as_view(), name='login-api'),
    path('api/register/', RegisterAPIView.as_view(), name='register-api'),
]

ntushb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('login.urls')),
    path('main_p/', include('main_p.urls')),
    path('order/', include('order.urls')),
    path('self_info/', include('self_info.urls')),
    path('evaluate/', include('evaluate.urls')),
    path('admin_page/', include('admin_page.urls')),
]

order/urls.py
from django.urls import path
from . import views
from .api_views import SaleOrderAPIView
from .api_views import WantOrderAPIView
from .api_views import SaleOrderDetailAPIView
from .api_views import WantOrderDetailAPIView
from .api_views import ReceiveAPIView

app_name = 'order'
urlpatterns = [
    path('', views.index, name='index'),
    path('want_order/<int:user_id>/', views.want_order, name='want_order'),
    path('sale_order/<int:user_id>/', views.sale_order, name='sale_order'),
    path('want_order/<int:user_id>/detail/<int:order_id>', views.want_order_detail, name='want_order_detail'),
    path('sale_order/<int:user_id>/detail/<int:order_id>', views.sale_order_detail, name='sale_order_detail'),
    path('receive/<int:user_id>/<int:poster_id>/<int:order_id>/<str:type>', views.receive, name='receive'),
    path('api/sale_order/<int:user_id>/<int:page>', SaleOrderAPIView.as_view(), name='sale-order-api'),
    path('api/want_order/<int:user_id>/<int:page>', WantOrderAPIView.as_view(), name='want-order-api'),
    path('api/sale_order_detail/<int:user_id>/<int:order_id>', SaleOrderDetailAPIView.as_view(),
         name='sale-order-detail-api'),
    path('api/want_order_detail/<int:user_id>/<int:order_id>', WantOrderDetailAPIView.as_view(), name='want-order-detail-api'),
    path('api/receive/<int:user_id>/<int:poster_id>/<int:order_id>/<str:type>', ReceiveAPIView.as_view(), name='receive-api'),
]

order/models.py
from django.db import models

# Create your models here.
class Book_simple:
    def __init__(self, isbn, price, title):
        self.isbn = isbn
        self.price = price
        self.title = title


class User:
    def __init__(self, user_id, user_name, email, role='user'):
        self.user_id = user_id
        self.user_name = user_name
        self.role = role
        self.email = email

order/views.py
from django.shortcuts import render,redirect
import requests
from main_p.models import SaleOrder
from main_p.models import WantOrder
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.urls import reverse
from django.http import HttpResponseNotAllowed
from itertools import chain



def index(request):
    return render(request, 'order/index.html')


def want_order(request, user_id):
    if request.method == 'GET':
        page = request.GET.get('page', 1)
        # Call the API with the page parameter
        api_url = f'http://localhost:8000/order/api/want_order/{user_id}/{page}'
        api_response = requests.get(api_url)
        api_data = api_response.json()

        # Get the orders from the API response
        orders = api_data.get('orders', [])
        nested_page_range = api_data.get('page_range')

        # Flatten the nested lists
        page_range = list(chain.from_iterable(nested_page_range))
        total_pages = 50000
        page = int(page)
        range_ = range(max(1, page - 5), min(page + 6, total_pages + 1))
        return render(request, 'order/want_order.html', {'orders': orders, 'user_id': user_id, 'page_range': page_range, 'range_': range_})
    return HttpResponseNotAllowed(['GET'])

def sale_order(request, user_id):
    if request.method == 'GET':
        page = request.GET.get('page', 1)
        # Call the API with the page parameter
        api_url = f'http://localhost:8000/order/api/sale_order/{user_id}/{page}'
        api_response = requests.get(api_url)
        api_data = api_response.json()

        # Get the orders from the API response
        orders = api_data.get('orders', [])
        nested_page_range = api_data.get('page_range')

        # Flatten the nested lists
        page_range = list(chain.from_iterable(nested_page_range))

        total_pages = 50000
        page = int(page)
        range_ = range(max(1, page - 5), min(page + 6, total_pages + 1))

        return render(request, 'order/sale_order.html', {'orders': orders, 'user_id': user_id, 'page_range': page_range, 'range_': range_})
    return HttpResponseNotAllowed(['GET'])
def want_order_detail(request, user_id, order_id):
    api_url = f'http://localhost:8000/order/api/want_order_detail/{user_id}/{order_id}'
    api_response = requests.get(api_url)
    api_response = api_response.json()
    books = api_response.get('books')
    poster_id = WantOrder.objects.get(orderid=order_id).userid.userid

    if request.method == 'POST':
        for key, value in request.POST.items():
                if value == 'receive':
                    return redirect('order:receive', type='want_order', user_id=user_id,poster_id=poster_id, order_id=order_id)
    return render(request, 'order/detail/want_order_detail.html', {'books':books,'user_id': user_id, 'order_id': order_id})

def sale_order_detail(request, user_id, order_id):
    api_url = f'http://localhost:8000/order/api/sale_order_detail/{user_id}/{order_id}'
    api_response = requests.get(api_url)
    api_response = api_response.json()
    books = api_response.get('books')
    poster_id = SaleOrder.objects.get(orderid=order_id).userid.userid
    if request.method == 'POST':
        for key, value in request.POST.items():
                if value == 'receive':
                    return redirect('order:receive', type='sale_order', user_id=user_id , poster_id=poster_id, order_id=order_id)
    return render(request, 'order/detail/sale_order_detail.html', {'books':books,'user_id': user_id, 'order_id': order_id})

def receive(request, user_id, poster_id, order_id, type):
    api_url = f'http://localhost:8000/order/api/receive/{user_id}/{poster_id}/{order_id}/{type}'
    api_response = requests.post(api_url)
    print(api_response.content)
    api_response = api_response.json()
    poster = api_response.get('poster')
    return render(request, 'order/receive.html', {'type':type, 'user_id':user_id, 'poster': poster, 'order_id': order_id})

order/templates/order/index.html
<!DOCTYPE html>
<html>
<head>
    <title>NTUSHB</title>
    <style>
        body {
            text-align: center;
        }
        #title {
            background-color: #f8f8f8;
            color: #333;
            padding: 10px 20px;
            text-align: left;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div id="title">
        <h1>NTUSHB</h1>
    </div>
</body>

order/templates/order/receive.html
<!DOCTYPE html>
<html>
<head>
    <title>NTUSHB</title>
    <style>
        body {
            text-align: center;
        }
        #login-form {
            margin: 50px auto;
            width: 30%;
            padding: 20px;
            border: 1px solid #ccc;
            box-shadow: 2px 2px 10px #ccc;
        }
        #title {
            background-color: #f8f8f8;
            color: #333;
            padding: 10px 20px;
            text-align: left;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div id="title">
        <!-- 像這樣可以顯示輸入的user的資訊 -->
        <h1>NTUSHB 聯絡po文者</h1>
        <p><a href="/main_p/{{user_id}}">回主頁</a></p>
    </div>
    
    <ul>
            <li>
                po文者資訊：
            </li>
            <li>
                使用者名稱: {{ poster.username }}
            </li>
            <li>
                使用者信箱: {{ poster.email }}
            </li>
    </ul>
</body>

order/templates/order/sale_order.html
<!DOCTYPE html>
<html>
<head>
    <title>NTUSHB</title>
    <style>
        body {
            text-align: center;
        }
        #login-form {
            margin: 50px auto;
            width: 30%;
            padding: 20px;
            border: 1px solid #ccc;
            box-shadow: 2px 2px 10px #ccc;
        }
        #title {
            background-color: #f8f8f8;
            color: #333;
            padding: 10px 20px;
            text-align: left;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div id="title">
        <!-- 像這樣可以顯示輸入的user的資訊 -->
        <h1>NTUSHB 販賣訂單</h1> 
        <p><a href="/main_p/{{user_id}}">回主頁</a></p>
    </div>
    {% for order in orders %}
    <h2><a href="{% url 'order:sale_order_detail' user_id=user_id order_id=order.order_id  %}">訂單編號: {{ order.order_id }}</a></h2>
    <ul>
        {% for book in order.books %}
            <li>
                書籍資訊：
                ISBN: {{ book.isbn }}, 
                價格: {{ book.price }},
                書名: {{ book.title }}
            </li>
        {% endfor %}
        <li>
            ---------------------------------------------------------------------------------------
        </li>
    </ul>
    {% endfor %}
    <form id="gotoPageForm" method="get" action="">
    <label for="page_number">Go to Page:</label>
    <input type="number" id="page_number" name="page" min="1" max="{{ page_range|length }}" required>
    <button type="button" onclick="gotoPage()">Go</button>
</form>

    {% for page in range_ %}
    <a href="?page={{ page }}">{{ page }}</a>
{% endfor %}


</body>

<script>
    function gotoPage() {
        var pageInput = document.getElementById("page_number").value;
        var maxPages = {{ page_range|length }};

        // Validate the input
        if (pageInput >= 1 && pageInput <= maxPages) {
            // Construct the URL with the selected page
            var url = window.location.pathname + '?page=' + pageInput;

            // Redirect to the new URL
            window.location.href = url;
        } else {
            alert("Invalid page number. Please enter a valid page between 1 and " + maxPages + ".");
        }
    }
</script>

order/templates/order/want_order.html
<!DOCTYPE html>
<html>
<head>
    <title>NTUSHB</title>
    <style>
        body {
            text-align: center;
        }
        #login-form {
            margin: 50px auto;
            width: 30%;
            padding: 20px;
            border: 1px solid #ccc;
            box-shadow: 2px 2px 10px #ccc;
        }
        #title {
            background-color: #f8f8f8;
            color: #333;
            padding: 10px 20px;
            text-align: left;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div id="title">
        <!-- 像這樣可以顯示輸入的user的資訊 -->
        <h1>NTUSHB 徵求訂單</h1> 
        <p><a href="/main_p/{{user_id}}">回主頁</a></p>
    </div>
	
	{% for page in page_range %}
    {% if page == current_page or page == pre_page or page == next_page %}
        <a href="?page={{ page }}">{{ page }}</a>
    {% endif %}
    {% endfor %}
	
    {% for order in orders %}
    <h2><a href="{% url 'order:want_order_detail' user_id=user_id order_id=order.order_id  %}">訂單編號: {{ order.order_id }}</a></h2>
    <ul>
        {% for book in order.books %}
            <li>
                書籍資訊：
                ISBN: {{ book.isbn }}, 
                書名: {{ book.title }}
            </li>
        {% endfor %}
        <li>
            ---------------------------------------------------------------------------------------
        </li>
    </ul>
    {% endfor %}
<form id="gotoPageForm" method="get" action="">
    <label for="page_number">Go to Page:</label>
    <input type="number" id="page_number" name="page" min="1" max="{{ page_range|length }}" required>
    <button type="button" onclick="gotoPage()">Go</button>
</form>

    {% for page in range_ %}
    <a href="?page={{ page }}">{{ page }}</a>
{% endfor %}


</body>

<script>
    function gotoPage() {
        var pageInput = document.getElementById("page_number").value;
        var maxPages = {{ page_range|length }};

        // Validate the input
        if (pageInput >= 1 && pageInput <= maxPages) {
            // Construct the URL with the selected page
            var url = window.location.pathname + '?page=' + pageInput;

            // Redirect to the new URL
            window.location.href = url;
        } else {
            alert("Invalid page number. Please enter a valid page between 1 and " + maxPages + ".");
        }
    }
</script>