evaluate/urls.py
from django.urls import path
from . import views
from .api_views import PersonalEvaluationAPIView
from .api_views import EvlueateAPIView
from .api_views import PostEvaluationAPIView

app_name = 'evaluate'
urlpatterns = [
    path('evaluate_detail/<int:user_id>/<int:pre_user_id>', views.evaluate_detail, name='evaluate_detail'),
    path('evaluate_user/<int:user_id>/', views.evaluate_user, name='evaluate_user'),
    path('evaluate_write/<int:user_id>/<int:target_id>', views.write_review, name='write_review'),
    path('api/personal_evaluation/<int:user_id>', PersonalEvaluationAPIView.as_view(), name='personal-evaluation-api'),
    path('api/evaluate/<int:user_id>', EvlueateAPIView.as_view(), name='evaluate-api'),
    path('api/post/<int:user_id>/<int:target_id>', PostEvaluationAPIView.as_view(), name='post-evaluation-api'),

]

login/urls.py
from django.urls import path
from . import views
from .api_views import LoginAPIView
from .api_views import RegisterAPIView

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('api/login/', LoginAPIView.as_view(), name='login-api'),
    path('api/register/', RegisterAPIView.as_view(), name='register-api'),
]

ntushb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('login.urls')),
    path('main_p/', include('main_p.urls')),
    path('order/', include('order.urls')),
    path('self_info/', include('self_info.urls')),
    path('evaluate/', include('evaluate.urls')),
    path('admin_page/', include('admin_page.urls')),
]

evaluate/models.py
from django.db import models
from main_p.models import Evaluate



# Create your models here.

evaluate/views.py
from django.shortcuts import render,redirect
import requests
from main_p.models import Users


app_name = 'evaluate'


def evaluate_detail(request, user_id, pre_user_id):
    api_url = f'http://localhost:8000/evaluate/api/personal_evaluation/{user_id}'
    api_response = requests.get(api_url)
    api_response = api_response.json()
    evaluates = api_response.get('evaluates')
    avg_score = api_response.get('avg_score')

    return render(request, 'evaluate/evaluate_detail.html',
                  {'user_id': user_id, 'avg_score': avg_score, 'evaluates': evaluates, "pre_user_id": pre_user_id})

def evaluate_user(request, user_id):
    api_url = f'http://localhost:8000/evaluate/api/evaluate/{user_id}'
    api_response = requests.get(api_url)
    api_response = api_response.json()
    received_buyers = api_response.get('receive_buyers')
    given_sellers = api_response.get('given_sellers')
    return render(request, 'evaluate/evaluate_user.html', {'user_id': user_id,
                                                           'received_buyers': received_buyers, 'given_sellers': given_sellers})


def write_review(request, user_id, target_id):
    target_user = Users.objects.get(userid= target_id)
    if request.method == 'POST':
        api_url = f'http://localhost:8000/evaluate/api/post/{user_id}/{target_id}'
        score = request.POST.get('score')
        comment = request.POST.get('comment')
        api_response = requests.post(api_url, data={'ranking': score, 'comment': comment})
        api_response = api_response.json()
        return redirect('evaluate:evaluate_detail', user_id=target_id, pre_user_id=user_id)
    return render(request, 'evaluate/evaluate_write.html', {'user_id': user_id, 'target_user': target_user})

evaluate/templates/evaluate/evaluate_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>NTUSHB</title>
    <style>
        body {
            text-align: center;
        }
        #title {
            background-color: #f8f8f8;
            color: #333;
            padding: 10px 20px;
            text-align: center;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
		table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
        }
		
    </style>
</head>
<body>
    <div id="title">
        <!-- 像這樣可以顯示輸入的user的資訊 -->
        <h1>NTUSHB 個人評價</h1> 
        <p><a href="/main_p/{{pre_user_id}}">回主頁</a></p>
    </div>
	<h2>平均分數：{{ avg_score }}</h2>
	<p>評價詳情：</p>
	<table>
        <thead>
            <tr>
                <th>分數</th>
                <th>評論</th>
            </tr>
        </thead>
        <tbody>
            {% for evaluate in evaluates %}
                <tr>
                    <td>{{ evaluate.ranking }}</td>
                    <td>{{ evaluate.comment }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

evaluate/templates/evaluate/evaluate_user.html
<!DOCTYPE html>
<html>
<head>
    <title>NTUSHB</title>
    <style>
        body {
            text-align: center;
        }
        #title {
            background-color: #f8f8f8;
            color: #333;
            padding: 10px 20px;
            text-align: center;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
		table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
        }
		
    </style>
</head>
<body>
    <div id="title">
        <!-- 像這樣可以顯示輸入的user的資訊 -->
        <h1>NTUSHB 評價使用者</h1> 
        <p><a href="/main_p/{{user_id}}">回主頁</a></p>
    </div>
	<h3>評價買家</h3>
	<ul>
        {% for buyer in received_buyers %}
            <li>
                {{ buyer.username }}
                <button onclick="location.href='{% url 'evaluate:write_review' user_id=user_id target_id=buyer.userid %}'">我要評論</button>
            </li>
        {% endfor %}
    </ul>
	<h3>評價賣家</h3>
	<ul>
        {% for seller in given_sellers %}
            <li>
                {{ seller.username }}
                <button onclick="location.href='{% url 'evaluate:write_review' user_id=user_id target_id=seller.userid %}'">我要評論</button>
            </li>
        {% endfor %}
    </ul>
	
</body>
</html>

evaluate/templates/evaluate/evaluate_write.html
<!-- write_review.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>填寫評論</title>
</head>
<body>
    <h1>填寫{{ target_user.username }}的評論 </h1>
        <p><a href="/main_p/{{user_id}}">回主頁</a></p>
	<form action="{% url 'evaluate:write_review' user_id=user_id target_id=target_user.userid%}" method="post">
        {% csrf_token %}<!--Django 的模板標籤-->
        <label for="score">評分：</label>
        <select name="score" id="score">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select>

        <label for="comment">評論：</label>
        <textarea name="comment" id="comment" rows="4"></textarea>

        <button type="submit">提交</button>
    </form>
</body>
</html>